const foodItems = [
    {
        id: 1,
        category: 'gujarati',
        name: 'Jalebi-fafda',
        Price: 80,
        img: 'images/Gujarati/jalebi_fafda.jpg',
    },
    {
        id: 2,
        category: 'gujarati',
        name: 'Khaman',
        Price: 160,
        img: 'images/Gujarati/khaman.jpg',
    },
    {
        id: 3,
        category: 'gujarati',
        name: 'Mohanthal',
        Price: 400,
        img: 'images/Gujarati/Mohanthal.jpg',
    },
    {
        id: 4,
        category: 'gujarati',
        name: 'Khandvi',
        Price: 130,
        img: 'images/Gujarati/Khandvi.jpg',
    },
    {
        id: 5,
        category: 'gujarati',
        name: 'Thepla',
        Price: 90,
        img: 'images/Gujarati/Thepla.jpg',
    },
    {
        id: 6,
        category: 'gujarati',
        name: 'gathiya',
        Price: 140,
        img: 'images/Gujarati/Gathiya.jpg',
    },
    {
        id: 7,
        category: 'gujarati',
        name: 'Ghooghra',
        Price: 50,
        img: 'images/Gujarati/ghooghra.jpeg',
    },
    {
        id: 8,
        category: 'gujarati',
        name: 'Patra',
        Price: 70,
        img: 'images/Gujarati/patra.jpg',
    },
    {
        id: 9,
        category: 'gujarati',
        name: 'Shrikhand',
        Price: 200,
        img: 'images/Gujarati/shrikhand.jpg',
    },
    {
        id: 10,
        category: 'gujarati',
        name: 'Fada-Lapsi',
        Price: 160,
        img: 'images/Gujarati/fada_lapsi.jpg',
    },
    {
        id: 11,
        category: 'punjabi',
        name: 'Chole Bhature',
        Price: 120,
        img: 'images/Punjabi/chole-bhature.jpg',
    },
    {
        id: 12,
        category: 'punjabi',
        name: 'Dal Makhani',
        Price: 60,
        img: 'images/Punjabi/Dal-Makhani.jpg',
    },
    {
        id: 13,
        category: 'punjabi',
        name: 'Malai-Lassi',
        Price: 40,
        img: 'images/Punjabi/Malai-Lassi.jpg',
    },
    {
        id: 14,
        category: 'punjabi',
        name: 'Paratha',
        Price: 60,
        img: 'images/Punjabi/Paratha.jpg',
    },
    {
        id: 15,
        category: 'punjabi',
        name: 'Aloo Samosa',
        Price: 30,
        img: 'images/Punjabi/Aloo-Samosa.jpg',
    },
    {
        id: 16,
        category: 'punjabi',
        name: 'Pinni',
        Price: 250,
        img: 'images/Punjabi/Pinni.jpg',
    },
    {
        id: 17,
        category: 'punjabi',
        name: 'Kada Prasad',
        Price: 90,
        img: 'images/Punjabi/kada-prasad.jpg',
    },
    {
        id: 18,
        category: 'punjabi',
        name: 'Makke di Roti',
        Price: 35,
        img: 'images/Punjabi/Makke-di-Roti.jpg',
    },
    {
        id: 19,
        category: 'punjabi',
        name: 'Paneer Tikka Masala',
        Price: 130,
        img: 'images/Punjabi/paneer-tikka-masala.jpeg',
    },
    {
        id: 20,
        category: 'punjabi',
        name: 'Sarson ka Saag',
        Price: 80,
        img: 'images/Punjabi/sarson-ka-saag.jpg',
    },
    {
        id: 21,
        category: 'south',
        name: 'Dosa',
        Price: 100,
        img: 'images/South/Dosa.jpg',
    },
    {
        id: 22,
        category: 'south',
        name: 'Idli',
        Price: 85,
        img: 'images/South/Idli.jpg',
    },
    {
        id: 23,
        category: 'south',
        name: 'Puttu',
        Price: 100,
        img: 'images/South/Puttu.jpg',
    },
    {
        id: 24,
        category: 'south',
        name: 'Appam',
        Price: 60,
        img: 'images/South/Appam.jpg',
    },
    {
        id: 25,
        category: 'south',
        name: 'Coconut Rice',
        Price: 200,
        img: 'images/South/Coconut-Rice.jpg',
    },
    {
        id: 26,
        category: 'south',
        name: 'Parotta',
        Price: 70,
        img: 'images/South/Parotta.jpg',
    },
    {
        id: 27,
        category: 'south',
        name: 'Pesarattu',
        Price: 110,
        img: 'images/South/Pesarattu.jpg',
    },
    {
        id: 28,
        category: 'south',
        name: 'Pongal',
        Price: 75,
        img: 'images/South/Pongal.jpg',
    },
    {
        id: 29,
        category: 'south',
        name: 'Sambar',
        Price: 25,
        img: 'images/South/Sambar.jpg',
    },
    {
        id: 30,
        category: 'south',
        name: 'Vada',
        Price: 40,
        img: 'images/South/Vada.jpg',
    }
]
export{foodItems};